2024-12-13 02:54:05,690 - bot.management.commands.run_bot - INFO - Buyruqlar o'rnatildi.
2024-12-13 02:54:05,690 - bot.management.commands.run_bot - INFO - Router ulandi.
2024-12-13 02:54:05,860 - root - INFO - Hamma foydalanuvchilarga bot ishga tushgani haqida xabar yuborildi.
2024-12-13 02:54:05,861 - aiogram.dispatcher - INFO - Start polling
2024-12-13 02:54:05,976 - aiogram.dispatcher - INFO - Run polling for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-13 02:54:29,464 - aiogram.event - INFO - Update id=970455543 is handled. Duration 375 ms by bot id=7495355868
2024-12-13 02:54:33,288 - aiogram.event - INFO - Update id=970455544 is handled. Duration 343 ms by bot id=7495355868
2024-12-13 02:54:37,698 - aiogram.event - INFO - Update id=970455545 is handled. Duration 125 ms by bot id=7495355868
2024-12-13 02:54:47,517 - aiogram.event - INFO - Update id=970455546 is handled. Duration 141 ms by bot id=7495355868
2024-12-13 11:02:59,284 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 11:02:59,289 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 11:03:10,729 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 11:04:38,675 - aiogram.event - INFO - Update id=970455547 is handled. Duration 671 ms by bot id=7495355868
2024-12-13 11:11:27,296 - aiogram.event - INFO - Update id=970455548 is handled. Duration 389 ms by bot id=7495355868
2024-12-13 12:22:51,985 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 12:22:51,993 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 12:22:52,946 - aiogram.dispatcher - INFO - Polling stopped
2024-12-13 12:22:53,401 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 12:22:53,533 - root - INFO - Hamma foydalanuvchilarga bot ishdan to'xtagani haqida xabar yuborildi.
2024-12-13 12:22:53,678 - aiogram.event - INFO - Update id=970455549 is not handled. Duration 264 ms by bot id=7495355868
2024-12-13 12:22:53,678 - aiogram.event - ERROR - Cause exception while process update id=970455549 by bot id=7495355868
TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 170, in make_request
    async with session.post(
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\connector.py", line 547, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\bot\headers\handlers.py", line 41, in welcome
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\bot.py", line 492, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\base.py", line 248, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 177, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
2024-12-13 12:22:53,765 - aiogram.event - INFO - Update id=970455550 is not handled. Duration 328 ms by bot id=7495355868
2024-12-13 12:22:53,766 - aiogram.event - ERROR - Cause exception while process update id=970455550 by bot id=7495355868
TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 170, in make_request
    async with session.post(
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\connector.py", line 547, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\bot\headers\handlers.py", line 41, in welcome
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\bot.py", line 492, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\base.py", line 248, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 177, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
2024-12-13 12:22:53,776 - aiogram.event - INFO - Update id=970455551 is not handled. Duration 343 ms by bot id=7495355868
2024-12-13 12:22:53,776 - aiogram.event - ERROR - Cause exception while process update id=970455551 by bot id=7495355868
TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 170, in make_request
    async with session.post(
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiohttp\connector.py", line 547, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\bot\headers\AdminBot.py", line 18, in admin
    await message.answer("Hello Word")
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\bot.py", line 492, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\base.py", line 248, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 177, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectionError: Connector is closed.
2024-12-13 12:22:53,793 - aiogram.dispatcher - INFO - Polling stopped for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-13 12:23:01,837 - bot.management.commands.run_bot - INFO - Buyruqlar o'rnatildi.
2024-12-13 12:23:01,838 - bot.management.commands.run_bot - INFO - Router ulandi.
2024-12-13 12:23:02,141 - root - INFO - Hamma foydalanuvchilarga bot ishga tushgani haqida xabar yuborildi.
2024-12-13 12:23:02,142 - aiogram.dispatcher - INFO - Start polling
2024-12-13 12:23:02,247 - aiogram.dispatcher - INFO - Run polling for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-13 12:23:09,857 - aiogram.event - INFO - Update id=970455552 is handled. Duration 375 ms by bot id=7495355868
2024-12-13 12:23:17,414 - aiogram.event - INFO - Update id=970455553 is handled. Duration 139 ms by bot id=7495355868
2024-12-13 12:23:20,814 - aiogram.event - INFO - Update id=970455554 is handled. Duration 781 ms by bot id=7495355868
2024-12-13 12:23:29,246 - aiogram.event - INFO - Update id=970455555 is handled. Duration 156 ms by bot id=7495355868
2024-12-13 14:28:18,586 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 14:28:18,688 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 14:28:20,425 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 14:28:21,039 - aiogram.event - INFO - Update id=970455556 is handled. Duration 592 ms by bot id=7495355868
2024-12-13 14:56:59,395 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 14:56:59,409 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 14:57:10,786 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 17:01:47,083 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 17:01:47,107 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 17:01:59,734 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 17:11:50,217 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2024-12-13 17:11:50,220 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 17:12:01,619 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 17:29:32,736 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-13 17:29:32,757 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-13 17:29:44,140 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 7495355868)
2024-12-13 18:17:26,948 - aiogram.event - INFO - Update id=970455558 is handled. Duration 453 ms by bot id=7495355868
2024-12-13 18:17:31,003 - aiogram.event - INFO - Update id=970455559 is handled. Duration 218 ms by bot id=7495355868
2024-12-13 18:17:34,084 - aiogram.event - INFO - Update id=970455560 is handled. Duration 125 ms by bot id=7495355868
2024-12-13 18:17:35,944 - aiogram.event - INFO - Update id=970455561 is handled. Duration 282 ms by bot id=7495355868
2024-12-15 01:45:27,969 - bot.management.commands.run_bot - INFO - Buyruqlar o'rnatildi.
2024-12-15 01:45:27,970 - bot.management.commands.run_bot - INFO - Router ulandi.
2024-12-15 01:45:28,179 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:45:28,298 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:45:28,430 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:45:28,430 - root - INFO - Hamma foydalanuvchilarga bot ishga tushgani haqida xabar yuborildi.
2024-12-15 01:45:28,431 - aiogram.dispatcher - INFO - Start polling
2024-12-15 01:45:28,542 - aiogram.dispatcher - INFO - Run polling for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-15 01:45:52,758 - aiogram.event - INFO - Update id=970455563 is handled. Duration 375 ms by bot id=7495355868
2024-12-15 01:45:56,738 - aiogram.event - INFO - Update id=970455564 is handled. Duration 469 ms by bot id=7495355868
2024-12-15 01:46:14,289 - aiogram.event - INFO - Update id=970455565 is not handled. Duration 16 ms by bot id=7495355868
2024-12-15 01:46:14,290 - aiogram.event - ERROR - Cause exception while process update id=970455565 by bot id=7495355868
AttributeError: 'CustomUser' object has no attribute 'fullname'
Traceback (most recent call last):
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\WebBot\bot\headers\handlers.py", line 64, in reg_user_contact
    full_name = user.fullname if user.fullname else message.from_user.username
                                 ^^^^^^^^^^^^^
AttributeError: 'CustomUser' object has no attribute 'fullname'
2024-12-15 01:47:32,420 - aiogram.dispatcher - INFO - Polling stopped
2024-12-15 01:47:32,780 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:32,898 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:33,022 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:33,158 - root - INFO - Hamma foydalanuvchilarga bot ishdan to'xtagani haqida xabar yuborildi.
2024-12-15 01:47:33,408 - aiogram.dispatcher - INFO - Polling stopped for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-15 01:47:39,989 - bot.management.commands.run_bot - INFO - Buyruqlar o'rnatildi.
2024-12-15 01:47:39,990 - bot.management.commands.run_bot - INFO - Router ulandi.
2024-12-15 01:47:40,212 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:40,349 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:40,491 - root - ERROR - Xabarni yuborishda xatolik yuz berdi: Telegram server says - Bad Request: chat not found
2024-12-15 01:47:40,659 - root - INFO - Hamma foydalanuvchilarga bot ishga tushgani haqida xabar yuborildi.
2024-12-15 01:47:40,659 - aiogram.dispatcher - INFO - Start polling
2024-12-15 01:47:40,770 - aiogram.dispatcher - INFO - Run polling for bot @CryptoCunsershipBot id=7495355868 - 'crypto-cunsership'
2024-12-15 01:47:46,575 - aiogram.event - INFO - Update id=970455566 is handled. Duration 405 ms by bot id=7495355868
2024-12-15 01:48:15,448 - aiogram.event - INFO - Update id=970455567 is handled. Duration 328 ms by bot id=7495355868
2024-12-15 01:48:17,633 - aiogram.event - INFO - Update id=970455568 is handled. Duration 437 ms by bot id=7495355868
2024-12-15 01:48:27,026 - aiogram.event - INFO - Update id=970455569 is handled. Duration 233 ms by bot id=7495355868
2024-12-15 02:21:12,699 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-15 02:21:12,723 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7495355868)
2024-12-15 02:29:28,754 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-12-15 02:29:28,756 - aiogram.dispatcher - WARNING - Sleep for 1.194843 seconds and try again... (tryings = 1, bot id = 7495355868)
2024-12-15 02:29:29,962 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 02:29:29,963 - aiogram.dispatcher - WARNING - Sleep for 1.632665 seconds and try again... (tryings = 2, bot id = 7495355868)
2024-12-15 02:29:31,609 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 02:29:31,609 - aiogram.dispatcher - WARNING - Sleep for 2.075254 seconds and try again... (tryings = 3, bot id = 7495355868)
2024-12-15 02:29:33,700 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 02:29:33,700 - aiogram.dispatcher - WARNING - Sleep for 2.561817 seconds and try again... (tryings = 4, bot id = 7495355868)
2024-12-15 02:50:49,248 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 02:50:49,252 - aiogram.dispatcher - WARNING - Sleep for 3.441175 seconds and try again... (tryings = 5, bot id = 7495355868)
2024-12-15 02:50:52,714 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 02:50:52,715 - aiogram.dispatcher - WARNING - Sleep for 4.405368 seconds and try again... (tryings = 6, bot id = 7495355868)
2024-12-15 11:19:00,010 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-15 11:19:00,011 - aiogram.dispatcher - WARNING - Sleep for 5.128051 seconds and try again... (tryings = 7, bot id = 7495355868)
2024-12-17 11:07:06,888 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:06,891 - aiogram.dispatcher - WARNING - Sleep for 5.028669 seconds and try again... (tryings = 8, bot id = 7495355868)
2024-12-17 11:07:11,942 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:11,946 - aiogram.dispatcher - WARNING - Sleep for 5.197086 seconds and try again... (tryings = 9, bot id = 7495355868)
2024-12-17 11:07:17,160 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:17,178 - aiogram.dispatcher - WARNING - Sleep for 5.078972 seconds and try again... (tryings = 10, bot id = 7495355868)
2024-12-17 11:07:22,266 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:22,267 - aiogram.dispatcher - WARNING - Sleep for 4.765051 seconds and try again... (tryings = 11, bot id = 7495355868)
2024-12-17 11:07:27,044 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:27,044 - aiogram.dispatcher - WARNING - Sleep for 4.843965 seconds and try again... (tryings = 12, bot id = 7495355868)
2024-12-17 11:07:31,904 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
2024-12-17 11:07:31,904 - aiogram.dispatcher - WARNING - Sleep for 4.854345 seconds and try again... (tryings = 13, bot id = 7495355868)
2024-12-17 11:07:47,147 - aiogram.dispatcher - INFO - Connection established (tryings = 14, bot id = 7495355868)
